#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE}")"

git pull origin main

do_it() {
	if [[ -n "${TERMUX_VERSION:-}" ]]; then
		rsync \
			--exclude .git/ \
			--exclude .gitattributes \
			--exclude bootstrap.sh \
			--exclude 'README*' \
			--exclude LICENSE \
			-avh --no-perms . ~
	else
		rsync \
			--exclude .termux \
			--exclude 'bin/termux-*' \
			--exclude .git/ \
			--exclude .gitattributes \
			--exclude bootstrap.sh \
			--exclude 'README*' \
			--exclude LICENSE \
			-avh --no-perms . ~
	fi
	. ~/.bash_profile
}

if [ "$1" = '--force' ] || [ "$1" = '-f' ]; then
	do_it
else
	read -rp 'This may overwrite existing files in your `$HOME` directory. Are you sure? (y/n) ' -n 1
	echo
	[[ "$REPLY" =~ ^[Yy]$ ]] && do_it
fi
unset do_it
