#!/bin/bash
set -euf

readonly HELP='$1 must be a path to a file
that contains old output from:
`apt-mark showmanual`
'

if [[ $# -lt 1 ]]
then
	printf '%s' "$HELP"
	exit 1
fi
readonly pack_ls="$(cat -- "$1")"

# to reduce time between auto-marking & installing,
# we must config now
echo \
'APT::Install-Recommends "0";
APT::Install-Suggests "0";' \
>> "${PREFIX:-}/etc/apt/apt.conf"
# Termux compatibility

# cleanup
apt-mark auto \*

apt update

# mark manual if existent.
# "--" for extra safety
apt -y install -- $pack_ls

# depends on:
# https://gist.github.com/Rudxain/2c4ac0ce7702da82da04707339c46a9c
apt-mark auto $(dpkg-list-essential)
# more cleanup, just-in-case
apt-mark -y minimize-manual

apt -y autopurge

apt -y upgrade
