# 0.18

# internal option used when displaying warning about
# obsolete config.saving_style.
# don't touch.
set config.saving_style_w = 1

# for SSD with battery
set infofiles.secure_save_fsync = 0

set connection.ssl.https_by_default = 1

# -1 expiration date
# 0 expire on session end, ignore expiration date
# 1+ expiration date, limit days
set cookies.max_age = 0

# ASK: mem or store?
set document.cache.memory.size = 16M

set terminal.xterm-256color.strike = 1
set terminal.xterm-256color.italic = 1

# https://github.com/rkd77/elinks/discussions/424
set document.colors.use_document_colors = 0
set document.colors.text = "#ccc"
set document.colors.background = "#000"

set document.colors.link = "#1af"
set document.colors.vlink = "#30f"

bind "main" "Tab" = "move-link-next"
bind "main" "Shift-Tab" = "move-link-prev"
bind "main" "Up" = "scroll-up"
bind "main" "Down" = "scroll-down"

