foreground=#ccc
background=#000
cursor=#fff

color0=#000
color1=#c00
color2=#0b0
color3=#bb0
color4=#04f
color5=#b0b
color6=#0bb
color7=#bbb

color8=#333
color9=#f30
color10=#0f0
color11=#ff0
color12=#37f
color13=#f0f
color14=#0ff
color15=#fff
