#!/bin/sh
#set -x
# support early debug in interactive mode;
# see also https://johannes.truschnigg.info/writing/2021-12_colodebug
if [ -n "${PS1:-}" ]; then
	PS4='+ $LINENO '
	[ -n "${BASH_VERSION:-}" ] && \
		PS4='+ ${BASH_SOURCE[0]} ${FUNCNAME[0]} $LINENO '
fi

export ENV="$HOME/.config/sh/rc"
case ":${PATH}:" in
	*:"$HOME/.local/bin":*);;
	*) export PATH="$HOME/.local/bin:$PATH";;
esac

export LANG=C.UTF-8

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
# https://github.com/rust-lang/rustup/issues/4532
export RUSTUP_AUTO_INSTALL=0

# JS/TS
[ -f "$HOME/.deno/env" ] && . "$HOME/.deno/env"

export HISTSIZE="$((1 << 16))"
export HISTFILESIZE="$HISTSIZE"
export HISTCONTROL=ignoreboth:erasedups

export INPUTRC="$HOME/.config/inputrc"

export PAGER='less -S'

# Helix
export EDITOR=hx VISUAL=hx

[ -n "${PS1:-}" ] && . "$HOME/.config/sh/aliases"
# SC2262
if [ -n "${PS1:-}" ]; then
	cdl() { cd -- "$1" && l; }
	cdla() { cd -- "$1" && la; }
	mkcd() { mkdir -p -- "$1" && cd -- "$1"; }

	fs() {
		# GNU Disk Usage
		if [ "$#" -gt 0 ]; then
			du -sb --si -- "$@"
		else
			du -abd1 --si | sort -hr
		fi
	}

	# https://github.com/Rudxain/loc.rs/blob/main/loc.sh
	loc() {
		impl() {
			grep -rIhc '[^[:space:]]' -- "$1" | awk '{s += $1} END {print s+0}'
		}
		if [ "$#" -gt 0 ]; then
			for p in "$@"; do
				echo "$(impl "$p") $p"
			done
		else
			for p in .[!.]* ./* ; do
				# emulate `nullglob`
				[ -e "$p" ] && echo "$(impl "$p") $p"
			done | sort -rn
		fi
	}

	# absolute frequencies, AKA "histogram".
	# ASK: support `-z`?
	counts() {
		if [ -t 1 ]; then
			sort | uniq -c | sort -nr
		else
			sort | uniq -c
		fi
	}

	# see also:
	# - https://github.com/mre/freq
	# - https://github.com/payload/tot-up
	fr3() {
		# word-like pattern;
		# doesn't recognize alt representations
		# such as HTML entities
		fr3_re="[[:alnum:]_'’]\{2,\}"
		# GNU grep
		if [ "$#" -gt 0 ]; then
			grep -oh "$@"
		elif [ -t 0 ]; then
			grep -rIoh "$fr3_re" .
		else
			grep -oh "$fr3_re" -
		fi | counts
		unset fr3_re
	}

	fd() {
		fd_type="${2:-}"
		# "smart"
		case "$1" in
			*[[:upper:]]*) fd_case=;;
			*) fd_case=i;;
		esac
		case "$1" in
			*/*) fd_name=path;;
			*) fd_name=name;;
		esac
		# sufix mode;
		# bypass with "*.ext" or ".ext*"
		case "$1" in
			.*) fd_query="*$1";;
			*) fd_query="*$1*";;
		esac

		set -- .
		[ -n "$fd_type" ] && set -- "$@" -type "$fd_type"
		set -- "$@" -${fd_case}${fd_name} "$fd_query"
		if [ -t 1 ]; then
			# strip "./" and WD
			# https://github.com/junegunn/fzf/issues/980#issuecomment-4017559731
			find "$@" | sed 's|^..||' | sort
		else
			find "$@"
		fi
		unset fd_type fd_case fd_name fd_query
	}

	# See also `git.joeyh.name/moreutils/combine`,
	# for alts that preserve order
	to_proper_set() { sort -u -- "$1"; }
	# union
	set_or() { sort -u -- "$1" "$2"; }
	# intersection (common elements).
	# WARN: if A or B have dupes (malformed sets),
	# this will print them
	set_and() { sort -- "$1" "$2" | uniq -d; }
	# difference / except / subtraction / NIMPLY gate.
	# WARN: if A has dupes (malformed set),
	# this will not print them
	set_minus() { sort -- "$1" "$2" "$2" | uniq -u; }
	# symmetric difference: (A-B)|(B-A), (A|B)-(A&B).
	# WARN: if A or B have dupes (malformed sets),
	# this will not print them
	set_xor() { sort -- "$1" "$2" | uniq -u; }

	# GNU Privacy Guard Agent
	if GPG_TTY="$(tty)"; then
		export GPG_TTY
	else
		unset GPG_TTY
		echo '⚠️ GPG_TTY unset'
	fi

	# ANSI esc-codes aren't POSIX
	PS1='$? $(case "$PWD" in
		"$HOME"*) printf %s "~${PWD#"$HOME"}";;
		*) printf %s "$PWD";;
	esac) Δ '
fi

# assert readable
if [ -s "$HOME/.config/sh/ext" ]; then
	. "$HOME/.config/sh/ext"
fi
