#!/bin/sh
#set -x
# support early debug in interactive mode;
# see also https://johannes.truschnigg.info/writing/2021-12_colodebug
if [ -n "${PS1:-}" ]; then
	PS4='+ $LINENO '
	[ -n "${BASH_VERSION:-}" ] && \
		PS4='+ ${BASH_SOURCE[0]} ${FUNCNAME[0]} $LINENO '
fi

export ENV="$HOME/.config/sh/rc"
case ":${PATH}:" in
	*:"$HOME/.local/bin":*);;
	*) export PATH="$HOME/.local/bin:$PATH";;
esac

export LANG=C.UTF-8

[ -f "$HOME/.cargo/env" ] && \. "$HOME/.cargo/env"
export RUSTUP_AUTO_INSTALL=0

# JS/TS
[ -f "$HOME/.deno/env" ] && \. "$HOME/.deno/env"

export HISTSIZE="$((1 << 16))"
export HISTFILESIZE="$HISTSIZE"
export HISTCONTROL=ignoreboth:erasedups

export INPUTRC="$HOME/.config/inputrc"

export PAGER='less -S'

# Helix
export EDITOR=hx VISUAL=hx

export TAPLO_CONFIG="$HOME/.config/taplo.toml"

[ -n "${PS1:-}" ] && \. "$HOME/.config/sh/aliases"
# SC2262
if [ -n "${PS1:-}" ]; then
	cdl() { cd -- "$1" && l; }
	cdla() { cd -- "$1" && la; }
	mkcd() { mkdir -p -- "$1" && cd -- "$1"; }

	fs() {
		# depends on GNU Disk Usage
		if [ "$#" -gt 0 ]; then
			du -sb --si -- "$@"
		else
			du -abd1 --si | sort -hr
		fi
	}

	fd() {
		fd_type="${2:-}"
		# "smart"
		case "$1" in
			*[[:upper:]]*) fd_case=;;
			*) fd_case=i;;
		esac
		case "$1" in
			*/*) fd_name=path;;
			*) fd_name=name;;
		esac
		# sufix mode;
		# bypass with "*.ext" or ".ext*"
		case "$1" in
			.*) fd_query="*$1";;
			*) fd_query="*$1*";;
		esac

		set -- .
		[ -n "$fd_type" ] && set -- "$@" -type "$fd_type"
		set -- "$@" -${fd_case}${fd_name} "$fd_query"
		if [ -t 1 ]; then
			# strip "./" and WD
			# https://github.com/junegunn/fzf/issues/980#issuecomment-4017559731
			find "$@" | sed 's|^..||' #| sort
		else
			find "$@"
		fi
		unset fd_type fd_case fd_name fd_query
	}

	# GNU Privacy Guard Agent
	if GPG_TTY="$(tty)"; then
		export GPG_TTY
	else
		unset GPG_TTY
		echo '⚠️ GPG_TTY unset'
	fi

	# ANSI esc-codes aren't POSIX
	PS1='$? $(
		case "$PWD" in
			"$HOME"*) printf %s "~${PWD##"$HOME"}";;
			*) printf %s "$PWD";;
		esac
	) Δ '
fi

# assert readable
if [ -s "$HOME/.config/sh/ext" ]; then
	\. "$HOME/.config/sh/ext"
fi
