#!/bin/sh
#set -x
# support early debug in interactive mode;
# see also https://johannes.truschnigg.info/writing/2021-12_colodebug
if [ -n "${PS1:-}" ]; then
	PS4='+ $LINENO '
	[ -n "${BASH_VERSION:-}" ] && \
		PS4='+ ${BASH_SOURCE[0]} ${FUNCNAME[0]} $LINENO '
fi

export ENV="$HOME/.config/sh/rc"
case ":${PATH}:" in
	*:"$HOME/.local/bin":*);;
	*) export PATH="$HOME/.local/bin:$PATH";;
esac

export LANG=C.UTF-8

export HISTSIZE="$((1 << 16))"
export HISTFILESIZE="$HISTSIZE"
export HISTCONTROL=ignoreboth:erasedups

export INPUTRC="$HOME/.config/inputrc"

export PAGER='less -S'

# Helix
export EDITOR=hx VISUAL=hx

[ -n "${PS1:-}" ] && \. "$HOME/.config/sh/aliases"
# SC2262
if [ -n "${PS1:-}" ]; then
	cdl() { cd -- "$1" && l; }
	cdla() { cd -- "$1" && la; }
	mkcd() { mkdir -p -- "$1" && cd -- "$1"; }

	fs() {
		# depends on GNU Disk Usage
		if [ "$#" -gt 0 ]; then
			du -sb --si -- "$@"
		else
			du -abd1 --si | sort -hr
		fi
	}

	fd() {
		# "smart"
		case "$1" in
			*[[:upper:]]*) fd_case=;;
			*) fd_case=i;;
		esac
		# sufix mode;
		# bypass with "*.ext" or ".ext*"
		case "$1" in
			.*) fd_query="*$1";;
			*) fd_query="*$1*";;
		esac
		if [ -n "$2" ]; then
			find . -type "$2" -${fd_case}name "$fd_query"
		else
			find . -${fd_case}name "$fd_query"
		fi |
			if [ -t 1 ]; then
				# strip "./" and WD
				# https://github.com/junegunn/fzf/issues/980#issuecomment-4017559731
				sed 's|^..||'
			else
				# is there another way to avoid duped code?
				cat
			fi
		unset fd_case fd_query
	}

	# GNU Privacy Guard Agent
	if GPG_TTY="$(tty)"; then
		export GPG_TTY
	else
		unset GPG_TTY
		echo '⚠️ GPG_TTY unset'
	fi

	# ANSI esc-codes aren't POSIX
	PS1='$? $(printf %s "$PWD" | sed "s:^$HOME:~:") Δ '
fi

# assert readable
if [ -s "$HOME/.config/sh/ext" ]; then
	\. "$HOME/.config/sh/ext"
fi
