#!/bin/bash
set -euf -o pipefail

readonly HELP='$1 must be a path to a file
that contains old output from:
`apt-mark showmanual`
'

if [[ $# -lt 1 ]]
then
	printf '%s' "$HELP"
	exit 1
fi
readonly pack_ls="$(cat -- "$1")"

# to reduce time between auto-marking & installing,
# we must config now
cp apt.conf "${PREFIX:-}/etc/apt/apt.conf"
# Termux compatibility

# cleanup
apt-mark auto \*

apt-get update

# mark manual if existent.
# "--" for extra safety
apt-get -y install -- $pack_ls

apt-mark auto $(./dpkg-list-essential)
# more cleanup, just-in-case
apt-mark minimize-manual

apt autopurge

apt-get -y upgrade

mv path.sh "${PREFIX:-}/etc/profile.d/"

mv apt-purge-retro "${PREFIX:-/usr}/local/bin/"
chown root:root apt-purge-retro
chmod 755 "${PREFIX:-/usr}/local/bin/"*

# touchscreen support
echo 'MOZ_USE_XINPUT2 DEFAULT=1' >>/etc/security/pam_env.conf

./Enable_AppArmor
