#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	# 9 December 2021, at 00:51
	# https://wiki.nftables.org/wiki-nftables/index.php/Simple_ruleset_for_a_workstation#fw.inet.basic
	chain input {
		type filter hook input priority 0; policy drop;
		iif lo accept
		ct state established,related accept
		icmpv6 type { nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert } accept
	}
	chain forward {
		type filter hook forward priority filter;
	}
	chain output {
		type filter hook output priority filter;
	}
}
