#!/bin/sh
set -euf
# https://wiki.debian.org/AppArmor/HowToUse#Enable_AppArmor
sudo mkdir -p /etc/default/grub.d
echo 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT apparmor=1 security=apparmor"' \
  | sudo tee /etc/default/grub.d/apparmor.cfg
sudo update-grub
# user should choose when to do so
#sudo reboot
