#!/bin/sh
#shellcheck disable=SC2139

alias reload='exec ${SHELL} -l'

alias paths='echo -e ${PATH//:/\\n}'

# the only thing MS did right /j
alias cls=clear

# raw strs
alias say="printf '%s\n'"

# Termux doesn't have the symlink
alias open=xdg-open

# safety
alias cp='cp -i'
alias mv='mv -i'
alias ln='ln -i'
alias rm='rm -i'

# emulate Busybox
alias nuke='rm -rf --'

# this may look confusing,
# as `.` sources files
alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~' # same as `cd` (0 args)?
alias -- -='cd -'

if [ -n "${TERMUX_VERSION:-}" ]; then
	# I hate Samsung, but dex is a good short name
	alias cdex="cd $EXTERNAL_STORAGE"

	alias cbg=termux-clipboard-get
	alias cbs=termux-clipboard-set
else
	alias cdex='cd ~/Desktop'

	alias cbg=wl-paste
	alias cbs=wl-copy
fi

if [ -x "${PREFIX:-/usr}/bin/dircolors" ]
then
	# assume GNU flavor
	f='--color=auto'
	#shellcheck disable=SC2015
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls="ls $f"
	alias dir="dir $f"
	alias vdir="vdir $f"

	# `GREP_OPTIONS="--color=auto"` is deprecated, hence these
	alias grep="grep $f"
	unset f
fi

alias la='ls -A'
alias ll='ls -lF'
alias lal='ls -AlF'
# list only directories
alias lsd="ls -l | grep --color=never '^d'"

# canonicalize
command -v hd > /dev/null || alias hd='hexdump -C'
# some systems have this symlinked

# intuitive map fn
alias map='xargs -n1'
# is `grep` equivalent to `filter`?
# what about `fold`/`reduce`?
