#!/bin/sh
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"

export PATH="$HOME/bin:$PATH"

export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

export HISTSIZE="$((1 << 12))"
export HISTFILESIZE="$HISTSIZE"
export HISTCONTROL=ignoreboth:erasedups

export PAGER='less -S'
