#!/bin/sh
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"

export PATH="$HOME/bin:$PATH"

# Rust
[ -f "$HOME/.cargo/env" ] && \. "$HOME/.cargo/env"

export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

export HISTSIZE="$((1 << 12))"
export HISTFILESIZE="$HISTSIZE"
export HISTCONTROL=ignoreboth:erasedups

export PAGER='less -S'

# Helix
export EDITOR=hx VISUAL=hx

# NodeJS
export NODE_REPL_HISTORY_SIZE="$((HISTSIZE >> 2))"
export NODE_REPL_MODE=strict

# GNU Privacy Guard
if GPG_TTY=$(tty); then
	export GPG_TTY
else
	unset GPG_TTY
	echo '⚠️ GPG_TTY unset'
fi

export TAPLO_CONFIG="$HOME/.config/taplo.toml"
