#!/bin/sh

mkcd() {
	mkdir -p "$@" && \
	# https://stackoverflow.com/a/1853993
	for last;do true;done && \
	cd "$last" #"$_"
	# is exit-code preserved?
}
cdls() {
	# is there a way to
	# pass all but last arg to `ls`?
	# that way, we can pass only the last arg to cd
	cd "$@" && ls
}

sizeof() {
	stat -Lc'%s' -- "$1"
}

dusort() {
	du "${1:-.}" -hd1 2>/dev/null | sort -h
}
