#!/bin/sh

mkcd() {
	mkdir -p "$@" && \
	# https://stackoverflow.com/a/1853993
	for last;do true;done && \
	cd "$last" #"$_"
	# is exit-code preserved?
}
cdls() {
	# is there a way to
	# pass all but last arg to `ls`?
	# that way, we can pass only the last arg to cd
	cd "$@" && ls
}

fs() {
	if [ "$#" -gt 0 ]; then
		du -sbh -- "$@"
	else
		# `--` is a micro-optimization
		du -sbh -- .[!.]* ./* | sort -h
	fi
}
