#!/bin/sh
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"

PATH="$PATH:$HOME/.local/bin"

# Rust
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# NodeJS & NPM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

export PATH
