#!/bin/sh

if [ -d "$HOME/bin" ]; then
	PATH="$HOME/bin:$PATH"
fi
PATH="$PATH:$HOME/.local/bin"

# Rust
if [ -f "$HOME/.cargo/env" ]; then
	. "$HOME/.cargo/env"
fi

# Golang
if [ -d "$HOME/go/bin" ]; then
	PATH="$PATH:$HOME/go/bin"
fi

export PATH
