#!/bin/sh
# Android
if [ -d /system/bin ]; then
	PATH="$PATH:/system/bin"
fi

if [ -d "$HOME/bin" ]; then
	PATH="$HOME/bin:$PATH"
fi
PATH="$PATH:$HOME/.local/bin"

# Rust
if [ -d "$HOME/.cargo/bin" ]; then
	PATH="$PATH:$HOME/.cargo/bin"
fi

export PATH
