#!/bin/sh
set -u # intentional

for f in ~/.sh/{path,exports,aliases,fns,extra}
do
	[ -r "$f" ] && [ -f "$f" ] && . "$f"
done
unset f

# friendlier for non-text input files
[ -x "$PREFIX/bin/lesspipe" ] && eval "$(SHELL=/bin/sh lesspipe)"
