#!/bin/sh
set -u # intentional

# friendlier for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

for f in ~/.sh/*; do
	[ -r "$f" ] && [ -f "$f" ] && \
	# guard against ♾️ recursive sourcing
	[ "$f" != ~/.sh/profile ] && . "$f"
done
