#!/bin/sh

# login-ish
[ -z "${__rxdf_exported:-}" ] && \. "$HOME/.sh/exports"

# interactive
if [ -n "${PS1:-}" ]; then
	for f in aliases fns prompt; do
		\. "$HOME/.sh/$f"
	done

	# GNU Privacy Guard Agent
	if GPG_TTY="$(tty)"; then
		export GPG_TTY
	else
		unset GPG_TTY
		echo '⚠️ GPG_TTY unset'
	fi

	# NodeJS & NPM
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

# assert readable file
[ -s "$HOME/.sh/ext" ] && \. "$HOME/.sh/ext"
