# https://github.com/helix-editor/helix/discussions/10281
[theme]
light = "everforest_light"
dark = "everforest_dark"
fallback = "dl" # for GNOME and Termux

[editor]
# rm `line-numbers`, because statusline is enough
gutters.layout = ["diagnostics", "spacer", "diff"]
word-completion = { enable = true, trigger-length = 3 }
cursorline = true
cursor-shape = { normal = "block", insert = "bar", select = "underline" }

[editor.statusline]
# no "mode"
left = [
	"spinner",
	"file-name",
	"read-only-indicator",
	"file-modification-indicator",
]
# `total-line-numbers` is an alt for `position-percentage`.
# Despite my love for fractions, "%" is complementary
# (presentation-wise, not information-wise)
# and it's always short
right = [
	"diagnostics",
	"selections",
	"register",
	"position-percentage",
	"position",
	"file-encoding",
]

[editor.lsp]
display-inlay-hints = true
inlay-hints-length-limit = 16
display-progress-messages = true
