[[language]]
name = "toml"
# https://github.com/tamasfe/taplo/issues/580#issuecomment-2004174721
roots = ["."]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true


[[language]]
name = "json"
indent = { tab-width = 3, unit = "\t" }
# I don't like redundant indent
auto-format = false

[language-server.vscode-json-language-server.config]
provideFormatter = true
[language-server.vscode-json-language-server.config.json]
validate.enable = true
format.enable = true
keepLines.enable = true


[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
indent = { tab-width = 4, unit = "\t" }
auto-format = true

# it seems the mere presence of this table overrides *ALL* defaults,
# so I have to copy all the defaults from here:
# https://github.com/helix-editor/helix/blob/81708b70e685426716999e1278b7373292e797e9/languages.toml#L196-L203
[language-server.typescript-language-server.config.javascript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = false
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true
includeInlayVariableTypeHintsWhenTypeMatchesName = false

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
indent = { tab-width = 4, unit = "\t" }
auto-format = true

# https://github.com/typescript-language-server/typescript-language-server/blob/184c60de3308621380469d6632bdff2e10f672fd/docs/configuration.md?plain=1#L164-L172
# https://github.com/helix-editor/helix/blob/81708b70e685426716999e1278b7373292e797e9/languages.toml#L187-L194
[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = false
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true
includeInlayVariableTypeHintsWhenTypeMatchesName = false


[[language]]
name = "markdown"
soft-wrap.enable = true
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "html"
indent = { tab-width = 3, unit = "\t" }

[[language]]
name = "css"
indent = { tab-width = 3, unit = "\t" }

[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "bash" # um, actually 🤓,
# I'd just like to interject for a moment.
# What you're refering to as "Bash", is in fact, POSIX/Ksh/Dash/Bash/Zsh/Fish,
# or as I've recently taken to calling it, *sh.
# Bash is a shell, but it's just one of many shells supported by "Bash-LSP",
#
# Many computer users run a modified version of the POSIX shell (such as Dash)
# every day, without realizing it.
# Through a peculiar turn of events,
# the version of POSIX-sh which is widely used today is often called "Bash",
# and many of its users are not aware that it is basically the POSIX-sh.
#
# There really is a Bash, and most people are using it,
# but it is just one shell among many.
indent = { tab-width = 4, unit = "\t" }

# `indent` controlled by `rustfmt`
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "go"
formatter.command = "goimports"
auto-format = true
