[[language]]
name = "toml"
# https://github.com/tamasfe/taplo/issues/580#issuecomment-2004174721
roots = ["."]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true


[[language]]
name = "json"
# I don't like redundant indent
auto-format = false

[language-server.vscode-json-language-server.config]
provideFormatter = true
[language-server.vscode-json-language-server.config.json]
validate.enable = true
format.enable = true
keepLines.enable = true


[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
auto-format = true

# it seems the mere presence of this table overrides *ALL* defaults,
# so I have to copy all the defaults from here:
# https://github.com/helix-editor/helix/blob/81708b70e685426716999e1278b7373292e797e9/languages.toml#L196-L203
[language-server.typescript-language-server.config.javascript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = false
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true
includeInlayVariableTypeHintsWhenTypeMatchesName = false

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
auto-format = true

# https://github.com/typescript-language-server/typescript-language-server/blob/184c60de3308621380469d6632bdff2e10f672fd/docs/configuration.md?plain=1#L164-L172
# https://github.com/helix-editor/helix/blob/81708b70e685426716999e1278b7373292e797e9/languages.toml#L187-L194
[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = false
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true
includeInlayVariableTypeHintsWhenTypeMatchesName = false


[[language]]
name = "python"
language-servers = ["pyright"]

# `indent` controlled by `rustfmt`
[language-server.rust-analyzer.config.check]
command = "clippy"
workspace = false
[language-server.rust-analyzer.config.cachePriming]
enable = false

[[language]]
name = "go"
formatter.command = "goimports"
auto-format = true
